# this is here so that keda can scale the proxy itself in the future
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cscaler-external-scaler
spec:
  scaleTargetRef:
    kind: Deployment
    name: cscaler-proxy
  maxReplicaCount: 1000 # Optional. Default: 100
  minReplicaCount: 1
  cooldownPeriod: 10
  pollingInterval: 1
  triggers:
    - type: external
      metadata:
        scalerAddress: "{{ .Values.proxyGRPCSvcName }}.{{ .Release.Namespace }}:{{ .Values.proxyGRPCSvcPort }}"
