apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cscaler-proxy
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ["", "apps", "scaledobjects.keda.sh", "keda.k8s.io"] # "" indicates the core API group
  resources: ["deployments", "services", "scaledobjects"]
  verbs: ["get", "watch", "list", "create", "delete"]
