apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.proxyAdminSvcName }}
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ .Values.proxyAdminSvcName }}
    app: cscaler
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: ClusterIP
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: {{ .Values.proxyAdminSvcPort }}
  selector:
    name: cscaler-proxy
    app: {{ template "fullname" . }}
    release: "{{ .Release.Name }}"
